COOKIE_SECRET: example

PORT: 80
PROCESS_NUM: 1
DEBUG: 0

HEALTH_CHECK_PERIOD: 5

APP_LOG_PATH: app.log
GEN_LOG_PATH: gen.log
ACC_LOG_PATH: access.log

REDIS_HOST:
REDIS_PORT:
REDIS_DB:
REDIS_PASSWD:

MYSQL_HOST:
MYSQL_PORT:
MYSQL_DATABASE:
MYSQL_USER:
MYSQL_PASSWORD: