COOKIE_SECRET: example

PORT: 8009
PROCESS_NUM: 1

HEALTH_CHECK_PERIOD: 5

APP_LOG_PATH: app.log
GEN_LOG_PATH: gen.log
ACC_LOG_PATH: access.log

Redis_Server:
  host:
  port:
  db:
  password:

Mysql_Server:
  host:
  port:
  db:
  user:
  password:
