version: "3"

volumes:
  production_mysql_data: {}
  production_mysql_data_backups: {}

services:
  tornado: &tornado
    build:
      context: .
      dockerfile: compose/production/tornado/Dockerfile
    image: app_production_tornado
    depends_on:
      - mysql
      - redis
    env_file:
      - ./.envs/.production/.tornado
      - ./.envs/.production/.mysql
    ports:
      - "0.0.0.0:8000:80"
    command: /start

  mysql:
    image: mysql:5.7
    volumes:
      - local_mysql_data:/var/lib/mysql
    env_file:
      - .envs/.local/.mysql
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  redis:
    image: redis:3.2

  celeryworker:
    <<: *tornado
    image: app_production_celeryworker
    depends_on:
      - redis
      - mysql
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *tornado
    image: app_production_celerybeat
    depends_on:
      - redis
      - mysql
    ports: []
    command: /start-celerybeat

  flower:
    <<: *tornado
    image: app_production_flower
    ports:
      - "5555:5555"
    command: /start-flower
